# Targets
all: doWhileExmaple kaffeautomat

doWhileExmaple: doWhileExmaple.cpp
	$(CXX) $(CXXFLAGS) -o doWhileExmaple doWhileExmaple.cpp

kaffeautomat: kaffeautomat.cpp
	$(CXX) $(CXXFLAGS) -o kaffeautomat kaffeautomat.cpp
